/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import canvas.MyShape;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Shape;
import java.awt.geom.Area;
import java.awt.image.BufferedImage;
import java.util.Random;
import javax.swing.JColorChooser;

/**
 *
 * @author Dann
 */
public class Menu extends javax.swing.JFrame
{

    //Variables booleandas que ayudan a detectar que tipo de seleccion se esta usando
    public static boolean selected = false;
    public static boolean selectedM = false;
    public static boolean selectedT = false;
    //Variables que ayudan a colocarle atributos a una figura
    public static boolean setStrokeColor = false;
    public static Color strokeColor1 = null;
    public static Color strokeColor2 = null;
    public static BufferedImage bi;

    //Variables que ayudan a saber el tipo de color y contorno que se busca para una figura
    public static int tipo_ContornoT;

    /**
     * Creates new form Menu
     */
    public Menu()
    {
        initComponents();
        jBSelectStrokeAtributo2.setVisible(false);
        modoCBasico();
    }

    /**
     * Método encargado de bloquear las opciones que no se relacionen con el
     * modo de creacion basico.
     */
    public void modoCBasico()
    {
        jBCAvanzada.setEnabled(false);
        jBEdicion.setEnabled(false);
        jPOperacionesArea.setVisible(false);
        jPSeleccion.setVisible(false);
        modoEdicion(false);
    }

    /**
     * Método que bloquea los botones de las figuras segun el parametro
     * proporcionado.
     *
     * @param atr
     */
    public void bloqueaFigs(boolean atr)
    {
        jButton3.setEnabled(atr);
        jButton14.setEnabled(atr);
        jButton15.setEnabled(atr);
        jButton16.setEnabled(atr);
        jButton17.setEnabled(atr);
        jButton18.setEnabled(atr);
        jButton19.setEnabled(atr);
        jButton20.setEnabled(atr);
        jButton4.setEnabled(atr);
        jButton5.setEnabled(atr);
        jButton6.setEnabled(atr);
        jButton7.setEnabled(atr);
        jButton8.setEnabled(atr);
        jButton9.setEnabled(atr);
        jButton10.setEnabled(atr);
        jButton11.setEnabled(atr);
        jButton12.setEnabled(atr);
        jButton13.setEnabled(atr);
        jButton26.setEnabled(atr);
    }

    /**
     * Método encargado de habilitar las opciones que no se relacionen con el
     * modo de creacion avanzada.
     */
    public void modoAvanzado(boolean atr)
    {
        jPSeleccion.setVisible(atr);
        jPOperacionesArea.setVisible(atr);
    }

    /**
     * Metodo encargado de desbloquear las opciones que no se relacionen con el
     * modo de edicion de figuras
     */
    public void modoEdicion(boolean atr)
    {
        //Panel de contorno
        jBSelectStrokeAtributo.setEnabled(atr);
        jBSelectStrokeAtributo2.setEnabled(atr);
        jBSelectStrokeRnd.setEnabled(atr);
        jRadioBColor.setEnabled(atr);
        jRadioGradiente.setEnabled(atr);
        jRadioBImagen.setEnabled(atr);
        jCTipoBorde.setEnabled(atr);
        jSGrosorBorde.setEnabled(atr);
        //Panel de relleno
        jBColorRelleno.setEnabled(atr);
        jBColorRellenoRnd.setEnabled(atr);
        jRCSolido.setEnabled(atr);
        jRCGradiente.setEnabled(atr);
        jRRellenoImagen.setEnabled(atr);
        //Transparencia y angulo
        jSTransparencia.setEnabled(atr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel6 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        vPnlAtributos = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPEContorno = new javax.swing.JPanel();
        jBSelectStrokeAtributo = new javax.swing.JButton();
        jBSelectStrokeRnd = new javax.swing.JButton();
        jRadioBColor = new javax.swing.JRadioButton();
        jRadioBImagen = new javax.swing.JRadioButton();
        jCTipoBorde = new javax.swing.JComboBox<>();
        jSGrosorBorde = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jRadioGradiente = new javax.swing.JRadioButton();
        jBSelectStrokeAtributo2 = new javax.swing.JButton();
        JPContorno = new canvas.GradientPanel();
        jPERelleno = new javax.swing.JPanel();
        jBColorRelleno = new javax.swing.JButton();
        jBColorRellenoRnd = new javax.swing.JButton();
        jRCSolido = new javax.swing.JRadioButton();
        jRCGradiente = new javax.swing.JRadioButton();
        jRRellenoImagen = new javax.swing.JRadioButton();
        jPanel12 = new javax.swing.JPanel();
        jPEAtributos = new javax.swing.JPanel();
        jSTransparencia = new javax.swing.JSlider();
        JPRotar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        vPnlModosEd = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jBCBasica = new javax.swing.JButton();
        jBCAvanzada = new javax.swing.JButton();
        jBEdicion = new javax.swing.JButton();
        jPSeleccion = new javax.swing.JPanel();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jPOperacionesArea = new javax.swing.JPanel();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        vpnlFiguras = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        vPnlDatos = new javax.swing.JPanel();
        javaDraw2DPanelM2 = new canvas.JavaDraw2DPanelM();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jPEContorno.setBackground(new java.awt.Color(204, 204, 255));
        jPEContorno.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contorno", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jBSelectStrokeAtributo.setText("Color 1");
        jBSelectStrokeAtributo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBSelectStrokeAtributoActionPerformed(evt);
            }
        });

        jBSelectStrokeRnd.setText("Random");
        jBSelectStrokeRnd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBSelectStrokeRndActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioBColor);
        jRadioBColor.setText("Color Solido");
        jRadioBColor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioBColorActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioBImagen);
        jRadioBImagen.setText("Imagen");
        jRadioBImagen.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jRadioBImagenStateChanged(evt);
            }
        });

        jCTipoBorde.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Continuo", "Punteado" }));
        jCTipoBorde.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                jCTipoBordeItemStateChanged(evt);
            }
        });
        jCTipoBorde.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCTipoBordeActionPerformed(evt);
            }
        });

        jSGrosorBorde.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        jSGrosorBorde.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jSGrosorBordeStateChanged(evt);
            }
        });

        jLabel4.setText("Grosor:");

        buttonGroup1.add(jRadioGradiente);
        jRadioGradiente.setText("Color Gradiente");
        jRadioGradiente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioGradienteActionPerformed(evt);
            }
        });

        jBSelectStrokeAtributo2.setText("Color 2");
        jBSelectStrokeAtributo2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBSelectStrokeAtributo2ActionPerformed(evt);
            }
        });

        JPContorno.setBackground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout JPContornoLayout = new javax.swing.GroupLayout(JPContorno);
        JPContorno.setLayout(JPContornoLayout);
        JPContornoLayout.setHorizontalGroup(
            JPContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );
        JPContornoLayout.setVerticalGroup(
            JPContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPEContornoLayout = new javax.swing.GroupLayout(jPEContorno);
        jPEContorno.setLayout(jPEContornoLayout);
        jPEContornoLayout.setHorizontalGroup(
            jPEContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEContornoLayout.createSequentialGroup()
                .addGroup(jPEContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jRadioBColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioGradiente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                    .addComponent(JPContorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPEContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEContornoLayout.createSequentialGroup()
                        .addComponent(jCTipoBorde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSGrosorBorde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jRadioBImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPEContornoLayout.createSequentialGroup()
                        .addComponent(jBSelectStrokeAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBSelectStrokeAtributo2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEContornoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBSelectStrokeRnd, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        jPEContornoLayout.setVerticalGroup(
            jPEContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEContornoLayout.createSequentialGroup()
                .addGroup(jPEContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEContornoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPEContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBSelectStrokeAtributo)
                            .addComponent(jBSelectStrokeAtributo2))
                        .addGap(18, 18, 18)
                        .addComponent(jBSelectStrokeRnd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE))
                    .addGroup(jPEContornoLayout.createSequentialGroup()
                        .addComponent(JPContorno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPEContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCTipoBorde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSGrosorBorde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEContornoLayout.createSequentialGroup()
                        .addGroup(jPEContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioBColor)
                            .addComponent(jRadioBImagen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioGradiente)
                        .addGap(4, 4, 4))))
        );

        jPERelleno.setBackground(new java.awt.Color(204, 204, 255));
        jPERelleno.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Relleno", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jBColorRelleno.setText("Seleccionar color");

        jBColorRellenoRnd.setText("Random");

        buttonGroup1.add(jRCSolido);
        jRCSolido.setText("Color Solido");

        buttonGroup1.add(jRCGradiente);
        jRCGradiente.setText("Color Gradiente");

        buttonGroup1.add(jRRellenoImagen);
        jRRellenoImagen.setText("Imagen");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPERellenoLayout = new javax.swing.GroupLayout(jPERelleno);
        jPERelleno.setLayout(jPERellenoLayout);
        jPERellenoLayout.setHorizontalGroup(
            jPERellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPERellenoLayout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPERellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBColorRellenoRnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBColorRelleno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPERellenoLayout.createSequentialGroup()
                .addComponent(jRCSolido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRCGradiente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRRellenoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPERellenoLayout.setVerticalGroup(
            jPERellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPERellenoLayout.createSequentialGroup()
                .addGroup(jPERellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPERellenoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBColorRelleno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBColorRellenoRnd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPERellenoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPERellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRRellenoImagen)
                    .addGroup(jPERellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRCSolido)
                        .addComponent(jRCGradiente)))
                .addContainerGap())
        );

        jPEAtributos.setBackground(new java.awt.Color(204, 204, 255));
        jPEAtributos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transparencia", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        javax.swing.GroupLayout jPEAtributosLayout = new javax.swing.GroupLayout(jPEAtributos);
        jPEAtributos.setLayout(jPEAtributosLayout);
        jPEAtributosLayout.setHorizontalGroup(
            jPEAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEAtributosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSTransparencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPEAtributosLayout.setVerticalGroup(
            jPEAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEAtributosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jSTransparencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        JPRotar.setBackground(new java.awt.Color(204, 204, 255));
        JPRotar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rotar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel8.setText("Transformar:");

        vCBox_AFFINE_TRANFORMATIONS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguna", "Mover", "Rotar", "Escalar", "Magia", "Reflejar" }));
        vCBox_AFFINE_TRANFORMATIONS.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vCBox_AFFINE_TRANFORMATIONSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPRotarLayout = new javax.swing.GroupLayout(JPRotar);
        JPRotar.setLayout(JPRotarLayout);
        JPRotarLayout.setHorizontalGroup(
            JPRotarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPRotarLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(vCBox_AFFINE_TRANFORMATIONS, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPRotarLayout.setVerticalGroup(
            JPRotarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPRotarLayout.createSequentialGroup()
                .addGroup(JPRotarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vCBox_AFFINE_TRANFORMATIONS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JPRotar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPEAtributos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPERelleno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPEContorno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPEContorno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPERelleno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPEAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JPRotar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout vPnlAtributosLayout = new javax.swing.GroupLayout(vPnlAtributos);
        vPnlAtributos.setLayout(vPnlAtributosLayout);
        vPnlAtributosLayout.setHorizontalGroup(
            vPnlAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vPnlAtributosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        vPnlAtributosLayout.setVerticalGroup(
            vPnlAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(vPnlAtributos, java.awt.BorderLayout.LINE_END);

        vPnlModosEd.setBackground(new java.awt.Color(255, 255, 255));
        vPnlModosEd.setPreferredSize(new java.awt.Dimension(1369, 110));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jBCBasica.setText("Creacion Basica");
        jBCBasica.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBCBasicaActionPerformed(evt);
            }
        });

        jBCAvanzada.setText("Creacion Avanzada");
        jBCAvanzada.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBCAvanzadaActionPerformed(evt);
            }
        });

        jBEdicion.setText("Edicion");
        jBEdicion.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBEdicionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jBCBasica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBCAvanzada))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jBEdicion)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCBasica)
                    .addComponent(jBCAvanzada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBEdicion)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        vPnlModosEd.add(jPanel5);

        jPSeleccion.setBackground(new java.awt.Color(255, 255, 255));
        jPSeleccion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selección", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 1, 13))); // NOI18N

        jToggleButton6.setText("Objeto");
        jToggleButton6.setToolTipText("Seleccion de un objeto");
        jToggleButton6.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jToggleButton6StateChanged(evt);
            }
        });
        jToggleButton6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jToggleButton6ActionPerformed(evt);
            }
        });

        jToggleButton8.setText("Multiple");
        jToggleButton8.setToolTipText("Seleccion Mutiple");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jToggleButton8ActionPerformed(evt);
            }
        });

        jToggleButton11.setText("Todos");
        jToggleButton11.setToolTipText("Seleccionar todo");
        jToggleButton11.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jToggleButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPSeleccionLayout = new javax.swing.GroupLayout(jPSeleccion);
        jPSeleccion.setLayout(jPSeleccionLayout);
        jPSeleccionLayout.setHorizontalGroup(
            jPSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSeleccionLayout.createSequentialGroup()
                .addComponent(jToggleButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton11)
                .addContainerGap())
        );
        jPSeleccionLayout.setVerticalGroup(
            jPSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSeleccionLayout.createSequentialGroup()
                .addGroup(jPSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton6)
                    .addComponent(jToggleButton8)
                    .addComponent(jToggleButton11))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        vPnlModosEd.add(jPSeleccion);

        jPOperacionesArea.setBackground(new java.awt.Color(255, 255, 255));
        jPOperacionesArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operaciones de Area", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 1, 13))); // NOI18N

        jToggleButton12.setText("A");
        jToggleButton12.setToolTipText("Creación basica de figuras");
        jToggleButton12.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jToggleButton12ActionPerformed(evt);
            }
        });

        jToggleButton13.setText("I");
        jToggleButton13.setToolTipText("");
        jToggleButton13.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jToggleButton13ActionPerformed(evt);
            }
        });

        jToggleButton14.setText("EO");
        jToggleButton14.setToolTipText("Modo edición");
        jToggleButton14.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jToggleButton14ActionPerformed(evt);
            }
        });

        jToggleButton15.setText("S");
        jToggleButton15.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jToggleButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPOperacionesAreaLayout = new javax.swing.GroupLayout(jPOperacionesArea);
        jPOperacionesArea.setLayout(jPOperacionesAreaLayout);
        jPOperacionesAreaLayout.setHorizontalGroup(
            jPOperacionesAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOperacionesAreaLayout.createSequentialGroup()
                .addComponent(jToggleButton12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton15))
        );
        jPOperacionesAreaLayout.setVerticalGroup(
            jPOperacionesAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOperacionesAreaLayout.createSequentialGroup()
                .addGroup(jPOperacionesAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton12)
                    .addComponent(jToggleButton13)
                    .addComponent(jToggleButton14)
                    .addComponent(jToggleButton15))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        vPnlModosEd.add(jPOperacionesArea);

        jPanel2.add(vPnlModosEd, java.awt.BorderLayout.PAGE_START);

        vpnlFiguras.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Java2D Primitivos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.setLayout(new java.awt.GridLayout(4, 3));

        jButton3.setText("Linea");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton14.setText("Elipse");
        jButton14.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);

        jButton15.setText("Rectangulo");
        jButton15.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);

        jButton16.setText("Rectangulo R");
        jButton16.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16);

        jButton17.setText("Arco");
        jButton17.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17);

        jButton18.setText("C. Cuadratica");
        jButton18.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18);

        jButton19.setText("Curva Cubica");
        jButton19.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19);

        jButton20.setText("Poligono");
        jButton20.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton20);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Java2D Modificadas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel3.setLayout(new java.awt.GridLayout(4, 3));

        jButton4.setText("Corazon");
        jButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);

        jButton5.setText("Casa");
        jButton5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);

        jButton6.setText("Triangulo");
        jButton6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);

        jButton7.setText("Diamante");
        jButton7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);

        jButton8.setText("Estrella 5P");
        jButton8.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8);

        jButton9.setText("Estrella 4P");
        jButton9.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9);

        jButton10.setText("Flecha Der");
        jButton10.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10);

        jButton11.setText("Rayo");
        jButton11.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11);

        jButton12.setText("Reloj Arena");
        jButton12.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton12);

        jButton13.setText("Estrella 6P");
        jButton13.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton13);

        jButton26.setText("Murcielago");
        jButton26.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton26);

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Java2D Creadas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout vpnlFigurasLayout = new javax.swing.GroupLayout(vpnlFiguras);
        vpnlFiguras.setLayout(vpnlFigurasLayout);
        vpnlFigurasLayout.setHorizontalGroup(
            vpnlFigurasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vpnlFigurasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vpnlFigurasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
                .addContainerGap())
        );
        vpnlFigurasLayout.setVerticalGroup(
            vpnlFigurasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vpnlFigurasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jPanel2.add(vpnlFiguras, java.awt.BorderLayout.LINE_START);

        vPnlDatos.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout vPnlDatosLayout = new javax.swing.GroupLayout(vPnlDatos);
        vPnlDatos.setLayout(vPnlDatosLayout);
        vPnlDatosLayout.setHorizontalGroup(
            vPnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1181, Short.MAX_VALUE)
        );
        vPnlDatosLayout.setVerticalGroup(
            vPnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.add(vPnlDatos, java.awt.BorderLayout.PAGE_END);

        javaDraw2DPanelM2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        javax.swing.GroupLayout javaDraw2DPanelM2Layout = new javax.swing.GroupLayout(javaDraw2DPanelM2);
        javaDraw2DPanelM2.setLayout(javaDraw2DPanelM2Layout);
        javaDraw2DPanelM2Layout.setHorizontalGroup(
            javaDraw2DPanelM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
        javaDraw2DPanelM2Layout.setVerticalGroup(
            javaDraw2DPanelM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );

        jPanel2.add(javaDraw2DPanelM2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton15ActionPerformed
    {//GEN-HEADEREND:event_jButton15ActionPerformed
        selected = false;
        selectedM = false;
        javaDraw2DPanelM2.shapeType = javaDraw2DPanelM2.RECTANGLE;
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        selected = false;
        selectedM = false;
        javaDraw2DPanelM2.shapeType = javaDraw2DPanelM2.LINE2D;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton14ActionPerformed
    {//GEN-HEADEREND:event_jButton14ActionPerformed
        selected = false;
        selectedM = false;
        javaDraw2DPanelM2.shapeType = javaDraw2DPanelM2.ELLIPSE2D;
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton16ActionPerformed
    {//GEN-HEADEREND:event_jButton16ActionPerformed
        selected = false;
        selectedM = false;
        javaDraw2DPanelM2.shapeType = javaDraw2DPanelM2.ROUNDRECTANGLE2D;
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton17ActionPerformed
    {//GEN-HEADEREND:event_jButton17ActionPerformed
        selected = false;
        selectedM = false;
        javaDraw2DPanelM2.shapeType = javaDraw2DPanelM2.ARC2D;
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton18ActionPerformed
    {//GEN-HEADEREND:event_jButton18ActionPerformed
        selected = false;
        selectedM = false;
        javaDraw2DPanelM2.shapeType = javaDraw2DPanelM2.QUADCURVE2D;
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton19ActionPerformed
    {//GEN-HEADEREND:event_jButton19ActionPerformed
        selected = false;
        selectedM = false;
        javaDraw2DPanelM2.shapeType = javaDraw2DPanelM2.CUBICCURVE2D;
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton20ActionPerformed
    {//GEN-HEADEREND:event_jButton20ActionPerformed
        selected = false;
        selectedM = false;
        javaDraw2DPanelM2.shapeType = javaDraw2DPanelM2.POLYGON;
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        selected = false;
        selectedM = false;
        javaDraw2DPanelM2.shapeType = javaDraw2DPanelM2.HEART;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton5ActionPerformed
    {//GEN-HEADEREND:event_jButton5ActionPerformed
        selected = false;
        selectedM = false;
        javaDraw2DPanelM2.shapeType = javaDraw2DPanelM2.HOUSE;
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton6ActionPerformed
    {//GEN-HEADEREND:event_jButton6ActionPerformed
        selected = false;
        selectedM = false;
        javaDraw2DPanelM2.shapeType = javaDraw2DPanelM2.TRIANGLE;
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton7ActionPerformed
    {//GEN-HEADEREND:event_jButton7ActionPerformed
        selected = false;
        selectedM = false;
        javaDraw2DPanelM2.shapeType = javaDraw2DPanelM2.DIAMOND;
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton8ActionPerformed
    {//GEN-HEADEREND:event_jButton8ActionPerformed
        selected = false;
        selectedM = false;
        javaDraw2DPanelM2.shapeType = javaDraw2DPanelM2.STAR5;
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton9ActionPerformed
    {//GEN-HEADEREND:event_jButton9ActionPerformed
        selected = false;
        selectedM = false;
        javaDraw2DPanelM2.shapeType = javaDraw2DPanelM2.STAR4;
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton11ActionPerformed
    {//GEN-HEADEREND:event_jButton11ActionPerformed
        selected = false;
        selectedM = false;
        javaDraw2DPanelM2.shapeType = javaDraw2DPanelM2.LIGHTNING;
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton13ActionPerformed
    {//GEN-HEADEREND:event_jButton13ActionPerformed
        selected = false;
        selectedM = false;
        javaDraw2DPanelM2.shapeType = javaDraw2DPanelM2.STAR6;
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton10ActionPerformed
    {//GEN-HEADEREND:event_jButton10ActionPerformed
        selected = false;
        selectedM = false;
        javaDraw2DPanelM2.shapeType = javaDraw2DPanelM2.RIGHTARROW;
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton12ActionPerformed
    {//GEN-HEADEREND:event_jButton12ActionPerformed
        selected = false;
        selectedM = false;
        javaDraw2DPanelM2.shapeType = javaDraw2DPanelM2.SANDCLOCK;
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jToggleButton6ActionPerformed
    {//GEN-HEADEREND:event_jToggleButton6ActionPerformed
        if (!selected)
        {
            selected = true;
            selectedM = false;
            javaDraw2DPanelM2.shapeType = javaDraw2DPanelM2.NO_SELECTED;
            jToggleButton8.setEnabled(false);
            jToggleButton11.setEnabled(false);
        } else
        {
            selected = false;
            selectedM = false;
            javaDraw2DPanelM2.setSelectedRentagle();
            javaDraw2DPanelM2.repaint();
            jToggleButton8.setEnabled(true);
            jToggleButton11.setEnabled(true);
        }
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton26ActionPerformed
    {//GEN-HEADEREND:event_jButton26ActionPerformed
        selected = false;
        selectedM = false;
        javaDraw2DPanelM2.shapeType = javaDraw2DPanelM2.BAT;
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jBSelectStrokeAtributoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBSelectStrokeAtributoActionPerformed
    {//GEN-HEADEREND:event_jBSelectStrokeAtributoActionPerformed
        if (jBSelectStrokeAtributo.getText().equals("Color 1"))
        {
            JColorChooser Selectorcolor = new JColorChooser();
            strokeColor1 = Selectorcolor.showDialog(null, "Seleccione un Color", Color.BLUE);
            //Mandamos el color seleccionado al canvas (JavaDraw2DPanel)
            if (tipo_ContornoT == 1)
            {
                javaDraw2DPanelM2.strokeColor = strokeColor1;
                JPContorno.setC1(strokeColor1);
                JPContorno.repaint();
                javaDraw2DPanelM2.strokeTexture = null;
            } else
            {
                if (tipo_ContornoT == 2)
                {
                    javaDraw2DPanelM2.strokeTexture = new GradientPaint(0.0f, 0.0f, strokeColor1, 0.0f, 10.0f, strokeColor2, true);
                    JPContorno.setC1(strokeColor1);
                    JPContorno.repaint();
                }
            }

        } else
        {
            NewJDialog txt = new NewJDialog(this, true);
            txt.setVisible(true);
        }
    }//GEN-LAST:event_jBSelectStrokeAtributoActionPerformed

    private void jBSelectStrokeRndActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBSelectStrokeRndActionPerformed
    {//GEN-HEADEREND:event_jBSelectStrokeRndActionPerformed
        Random rand = new Random();
        int r = rand.nextInt(255);
        int g = rand.nextInt(255);
        int b = rand.nextInt(255);
        strokeColor1 = new Color(r, g, b);
        JPContorno.setBackground(strokeColor1);
        javaDraw2DPanelM2.strokeColor = strokeColor1;
    }//GEN-LAST:event_jBSelectStrokeRndActionPerformed

    private void jRadioBImagenStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jRadioBImagenStateChanged
    {//GEN-HEADEREND:event_jRadioBImagenStateChanged
        if (jRadioBImagen.isSelected())
        {
            jBSelectStrokeAtributo.setText("Imagen");
        } else
        {
            jBSelectStrokeAtributo.setText("Color 1");
        }
    }//GEN-LAST:event_jRadioBImagenStateChanged

    private void jCTipoBordeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCTipoBordeActionPerformed
    {//GEN-HEADEREND:event_jCTipoBordeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTipoBordeActionPerformed

    private void jCTipoBordeItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_jCTipoBordeItemStateChanged
    {//GEN-HEADEREND:event_jCTipoBordeItemStateChanged
        if (jCTipoBorde.getSelectedIndex() == 0)
        {
            BasicStroke bs = new BasicStroke(Integer.parseInt(jSGrosorBorde.getValue().toString()));
            javaDraw2DPanelM2.stroke = bs;
        } else
        {
            if (jCTipoBorde.getSelectedIndex() == 1)
            {
                float[] punteo1 =
                {
                    10.0f, 4.0f
                };
                BasicStroke bs = new BasicStroke(Integer.parseInt(jSGrosorBorde.getValue().toString()),
                        BasicStroke.CAP_ROUND,
                        BasicStroke.JOIN_MITER,
                        3.0f,
                        punteo1,
                        10.0f);
                javaDraw2DPanelM2.stroke = bs;
            }

        }
    }//GEN-LAST:event_jCTipoBordeItemStateChanged

    private void jSGrosorBordeStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jSGrosorBordeStateChanged
    {//GEN-HEADEREND:event_jSGrosorBordeStateChanged
        if (jCTipoBorde.getSelectedIndex() == 0)
        {
            BasicStroke bs = new BasicStroke(Integer.parseInt(jSGrosorBorde.getValue().toString()));
            javaDraw2DPanelM2.stroke = bs;
        } else
        {
            if (jCTipoBorde.getSelectedIndex() == 1)
            {
                float[] punteo1 =
                {
                    10.0f, 15.0f
                };
                BasicStroke bs = new BasicStroke(Integer.parseInt(jSGrosorBorde.getValue().toString()),
                        BasicStroke.CAP_ROUND,
                        BasicStroke.JOIN_MITER,
                        3.0f,
                        punteo1,
                        10.0f);
                javaDraw2DPanelM2.stroke = bs;
            }
        }
    }//GEN-LAST:event_jSGrosorBordeStateChanged

    private void jBSelectStrokeAtributo2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBSelectStrokeAtributo2ActionPerformed
    {//GEN-HEADEREND:event_jBSelectStrokeAtributo2ActionPerformed
        if (jBSelectStrokeAtributo2.getText().equals("Color 2"))
        {
            JColorChooser Selectorcolor = new JColorChooser();
            strokeColor2 = Selectorcolor.showDialog(null, "Seleccione un Color", Color.BLUE);
            JPContorno.setC1(strokeColor1);
            JPContorno.setC2(strokeColor2);
            //Mandamos el color seleccionado al canvas (JavaDraw2DPanel)
            javaDraw2DPanelM2.strokeColor = strokeColor2;
            javaDraw2DPanelM2.strokeTexture = new GradientPaint(0.0f, 0.0f, strokeColor1, 0.0f, 10.0f, strokeColor2, true);
            JPContorno.repaint();
        }
    }//GEN-LAST:event_jBSelectStrokeAtributo2ActionPerformed

    private void jRadioBColorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioBColorActionPerformed
    {//GEN-HEADEREND:event_jRadioBColorActionPerformed
        JPContorno.setTextura("Color");
        JPContorno.repaint();
        tipo_ContornoT = 1; //Color solido
    }//GEN-LAST:event_jRadioBColorActionPerformed

    private void jRadioGradienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioGradienteActionPerformed
    {//GEN-HEADEREND:event_jRadioGradienteActionPerformed
        if (jRadioGradiente.isSelected())
        {
            jBSelectStrokeAtributo2.setVisible(true);
            JPContorno.setTextura("Gr");
            tipo_ContornoT = 2; //Gradiente
        } else
        {
            jBSelectStrokeAtributo2.setVisible(false);
        }
    }//GEN-LAST:event_jRadioGradienteActionPerformed

    private void jToggleButton6StateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jToggleButton6StateChanged
    {//GEN-HEADEREND:event_jToggleButton6StateChanged


    }//GEN-LAST:event_jToggleButton6StateChanged

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jToggleButton8ActionPerformed
    {//GEN-HEADEREND:event_jToggleButton8ActionPerformed
        if (!selectedM)
        {
            selectedM = true;
            selected = false;
            jToggleButton6.setEnabled(false);
            jToggleButton11.setEnabled(false);
        } else
        {
            selectedM = false;
            selected = false;
            javaDraw2DPanelM2.setSelectedRentagle();
            javaDraw2DPanelM2.repaint();
            jToggleButton6.setEnabled(true);
            jToggleButton11.setEnabled(true);
        }

        javaDraw2DPanelM2.shapeType = javaDraw2DPanelM2.NO_SELECTED;
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton11ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jToggleButton11ActionPerformed
    {//GEN-HEADEREND:event_jToggleButton11ActionPerformed
        if (!selectedT)
        {
            selectedT = true;
            selected = false;
            selectedM = false;
            jToggleButton6.setEnabled(false);
            jToggleButton8.setEnabled(false);
            javaDraw2DPanelM2.mousePressed(null);
        } else
        {
            selectedT = false;
            selected = false;
            selectedM = false;
            javaDraw2DPanelM2.setSelectedRentagle();
            javaDraw2DPanelM2.repaint();
            jToggleButton6.setEnabled(true);
            jToggleButton8.setEnabled(true);
        }

        javaDraw2DPanelM2.shapeType = javaDraw2DPanelM2.NO_SELECTED;
    }//GEN-LAST:event_jToggleButton11ActionPerformed

    private void jBCBasicaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBCBasicaActionPerformed
    {//GEN-HEADEREND:event_jBCBasicaActionPerformed
        if (jBCBasica.isSelected())
        {
            jBCAvanzada.setEnabled(false);
            jBEdicion.setEnabled(false);
            //System.out.println("entre");
            jBCBasica.setSelected(false);
            bloqueaFigs(true);
        } else
        {
            jBCBasica.setSelected(true);
            jBCAvanzada.setEnabled(true);
            jBEdicion.setEnabled(true);
            //System.out.println("entre al true");
            bloqueaFigs(false);
            javaDraw2DPanelM2.shapeType = javaDraw2DPanelM2.NO_SELECTED;
        }
    }//GEN-LAST:event_jBCBasicaActionPerformed

    private void jBCAvanzadaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBCAvanzadaActionPerformed
    {//GEN-HEADEREND:event_jBCAvanzadaActionPerformed
        if (jBCAvanzada.isSelected())
        {
            modoAvanzado(true);
            jBCBasica.setEnabled(false);
            jBEdicion.setEnabled(false);
            jBCAvanzada.setSelected(false);

        } else
        {
            modoAvanzado(false);
            jBCBasica.setEnabled(true);
            jBEdicion.setEnabled(true);
            jBCAvanzada.setSelected(true);

        }
    }//GEN-LAST:event_jBCAvanzadaActionPerformed

    private void jBEdicionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBEdicionActionPerformed
    {//GEN-HEADEREND:event_jBEdicionActionPerformed
        if (jBEdicion.isSelected())
        {
            modoEdicion(true);
            jBCBasica.setEnabled(false);
            jBCAvanzada.setEnabled(false);
            jBEdicion.setSelected(false);
            jPSeleccion.setVisible(true);
        } else
        {
            modoEdicion(false);
            jBCBasica.setEnabled(true);
            jBCAvanzada.setEnabled(true);
            jBEdicion.setSelected(true);
            jPSeleccion.setVisible(false);
        }
    }//GEN-LAST:event_jBEdicionActionPerformed

    private void jToggleButton12ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jToggleButton12ActionPerformed
    {//GEN-HEADEREND:event_jToggleButton12ActionPerformed
        operaciones(1);
    }//GEN-LAST:event_jToggleButton12ActionPerformed

    private void jToggleButton13ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jToggleButton13ActionPerformed
    {//GEN-HEADEREND:event_jToggleButton13ActionPerformed
        operaciones(2);
    }//GEN-LAST:event_jToggleButton13ActionPerformed

    private void jToggleButton14ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jToggleButton14ActionPerformed
    {//GEN-HEADEREND:event_jToggleButton14ActionPerformed
        operaciones(3);
    }//GEN-LAST:event_jToggleButton14ActionPerformed

    private void jToggleButton15ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jToggleButton15ActionPerformed
    {//GEN-HEADEREND:event_jToggleButton15ActionPerformed
        operaciones(4);
    }//GEN-LAST:event_jToggleButton15ActionPerformed

    private void vCBox_AFFINE_TRANFORMATIONSActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vCBox_AFFINE_TRANFORMATIONSActionPerformed
    {//GEN-HEADEREND:event_vCBox_AFFINE_TRANFORMATIONSActionPerformed
        //Este cBOx es llamado desde Java2DPanel
    }//GEN-LAST:event_vCBox_AFFINE_TRANFORMATIONSActionPerformed

    public void operaciones(int opType)
    {
        Area s = new Area(); //Area que contenra todas nuestras figuras
        boolean figMadre = false; //Para agarrar la primer figura que se encuentra
        boolean figOperada = false; //
        MyShape figAux = null; //Figura auxiliar que se usara para recuperar las propiedades de la figura antigua

        //Primero recorremos todo el arreglo buscando la primer figura que existe en nuestro arreglo
        for (int i = 0; i < javaDraw2DPanelM2.shapes.size(); i++)
        {
            //Primero agarramos la primer figura del arreglo, de tal manera que si esta seleccionada y la figura madre es false entonces 
            //entramos y seleccionamos la misma.
            if (javaDraw2DPanelM2.shapes.get(i).getSelected() && !figMadre)
            {
                s = new Area(javaDraw2DPanelM2.shapes.get(i).getShape()); //Guardamos la figura como Area en S
                figMadre = true; //Hacemos true para que ya se tenga una figura madre de base
                figAux = javaDraw2DPanelM2.shapes.get(i);//Obtenemos los parametros de la figura madre (Color, relleno etc)
                javaDraw2DPanelM2.shapes.remove(i); //Eliminamos la figura madre del arreglo de shapes
                i--; //Le quitamos 1 para que no encuentre a la misma figura

                //Posteriormente si ya tenmos una figura madre recorremos las demas figuras
            } else if (javaDraw2DPanelM2.shapes.get(i).getSelected() && figMadre)
            {
                //Creamos un area con la figura que este seleccionada
                Area aAux = new Area(javaDraw2DPanelM2.shapes.get(i).getShape());
                //Dependiendo el caso que se proporcione hacemos la operacion boolena que corresponde
                switch (opType)
                {
                    case 1:
                        s.add(aAux);
                        break;
                    case 2:
                        s.intersect(aAux);
                        break;
                    case 3:
                        s.subtract(aAux);
                        break;
                    case 4:
                        s.exclusiveOr(aAux);
                        break;
                }
                //Removemos la figura que se tiene en el arreglo y se incluyo dentro del area
                javaDraw2DPanelM2.shapes.remove(i);
                //Cuando ya tenemos una Area hecha con minimo 2 figuras decimos que ya hay una figura con operaciones booleanas por lo que se procede a agregar
                figOperada = true;
                i--;
            }
        }

        if (figOperada)
        {
            Shape newShape = s;
            javaDraw2DPanelM2.shapes.add(new MyShape(newShape));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static canvas.GradientPanel JPContorno;
    private javax.swing.JPanel JPRotar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBCAvanzada;
    private javax.swing.JButton jBCBasica;
    private javax.swing.JButton jBColorRelleno;
    private javax.swing.JButton jBColorRellenoRnd;
    private javax.swing.JButton jBEdicion;
    private javax.swing.JButton jBSelectStrokeAtributo;
    private javax.swing.JButton jBSelectStrokeAtributo2;
    private javax.swing.JButton jBSelectStrokeRnd;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jCTipoBorde;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPEAtributos;
    private javax.swing.JPanel jPEContorno;
    private javax.swing.JPanel jPERelleno;
    private javax.swing.JPanel jPOperacionesArea;
    private javax.swing.JPanel jPSeleccion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRCGradiente;
    private javax.swing.JRadioButton jRCSolido;
    private javax.swing.JRadioButton jRRellenoImagen;
    private javax.swing.JRadioButton jRadioBColor;
    private javax.swing.JRadioButton jRadioBImagen;
    private javax.swing.JRadioButton jRadioGradiente;
    private javax.swing.JSpinner jSGrosorBorde;
    private javax.swing.JSlider jSTransparencia;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton8;
    private canvas.JavaDraw2DPanelM javaDraw2DPanelM2;
    public static final javax.swing.JComboBox<String> vCBox_AFFINE_TRANFORMATIONS = new javax.swing.JComboBox<>();
    private javax.swing.JPanel vPnlAtributos;
    private javax.swing.JPanel vPnlDatos;
    private javax.swing.JPanel vPnlModosEd;
    private javax.swing.JPanel vpnlFiguras;
    // End of variables declaration//GEN-END:variables
}
