/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import canvas.JavaDraw2DPanelM;
import java.awt.Image;
import java.awt.Label;
import java.awt.TexturePaint;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author kenit
 */
public class NewJDialog extends javax.swing.JDialog
{

    String filename;

    /**
     * Creates new form NewJDialog
     */
    public NewJDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    public void setImage(String tipo)
    {
        ImageIcon i1;
        ImageIcon i2;
        ImageIcon i3;
        JLabel i4 = new JLabel();
        i4.setBounds(5, 37, 151, 93);
        i4.setOpaque(true);
        switch (tipo)
        {
            case "boton":
                i1 = new ImageIcon(getClass().getResource("/images/button.png"));
                i2 = new ImageIcon(i1.getImage().getScaledInstance(jLImage.getWidth(), jLImage.getHeight(), Image.SCALE_DEFAULT));
                i3 = new ImageIcon(i1.getImage().getScaledInstance(i4.getWidth(), i4.getHeight(), Image.SCALE_DEFAULT));
                jLImage.setIcon(i2);
                i4.setIcon(i3);
                i4.setText("EEEEE");
                Menu.JPContorno.add(i4);
                filename = "/images/button.png";
                break;
            case "flamas":
                i1 = new ImageIcon(getClass().getResource("/images/flames.png"));
                i2 = new ImageIcon(i1.getImage().getScaledInstance(jLImage.getWidth(), jLImage.getHeight(), Image.SCALE_DEFAULT));
                i3 = new ImageIcon(i1.getImage().getScaledInstance(i4.getWidth(), i4.getHeight(), Image.SCALE_DEFAULT));
                jLImage.setIcon(i2);
                i4.setIcon(i3);
                Menu.JPContorno.add(i4);
                filename = "/images/flames.png";
                break;
            case "l_verde":
                i1 = new ImageIcon(getClass().getResource("/images/greeen.png"));
                i2 = new ImageIcon(i1.getImage().getScaledInstance(jLImage.getWidth(), jLImage.getHeight(), Image.SCALE_DEFAULT));
                i3 = new ImageIcon(i1.getImage().getScaledInstance(i4.getWidth(), i4.getHeight(), Image.SCALE_DEFAULT));
                jLImage.setIcon(i2);
                i4.setIcon(i3);
                Menu.JPContorno.add(i4);
                filename = "/images/greeen.png";
                break;
        }
    }

    private BufferedImage getImage(String filename)
    {
        // This time, you can use an InputStream to load
        try
        {
            // Grab the InputStream for the image.                    
            InputStream in = getClass().getResourceAsStream(filename);

            // Then read it.
            return ImageIO.read(in);
        } catch (IOException e)
        {
            System.out.println("The image was not loaded.");
            //System.exit(1);
        }

        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLImage = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Linterna verde");
        jRadioButton1.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jRadioButton1StateChanged(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Flamas");
        jRadioButton2.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jRadioButton2StateChanged(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Boton");
        jRadioButton3.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jRadioButton3StateChanged(evt);
            }
        });

        jLabel4.setText("Seleccione una imagen:");

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jLImage, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)
                        .addGap(38, 38, 38)
                        .addComponent(jRadioButton1))
                    .addComponent(jLImage, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton3StateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jRadioButton3StateChanged
    {//GEN-HEADEREND:event_jRadioButton3StateChanged
        if (jRadioButton3.isSelected())
        {
            setImage("boton");
        }
    }//GEN-LAST:event_jRadioButton3StateChanged

    private void jRadioButton2StateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jRadioButton2StateChanged
    {//GEN-HEADEREND:event_jRadioButton2StateChanged
        if (jRadioButton2.isSelected())
        {
            setImage("flamas");
        }

    }//GEN-LAST:event_jRadioButton2StateChanged

    private void jRadioButton1StateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jRadioButton1StateChanged
    {//GEN-HEADEREND:event_jRadioButton1StateChanged
        if (jRadioButton1.isSelected())
        {
            setImage("l_verde");
        }

    }//GEN-LAST:event_jRadioButton1StateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        BufferedImage in = getImage(filename);
        BufferedImage buffImg = new BufferedImage(in.getWidth(), in.getHeight(), BufferedImage.TYPE_INT_ARGB);
        TexturePaint tp = new TexturePaint(buffImg, new Rectangle2D.Double(10, 10, 50, 25));
        JavaDraw2DPanelM.strokeTexture = tp;
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                NewJDialog dialog = new NewJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLImage;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables
}
